CLI_ISSUES = [
  { "editionID": "CLI13", "thumbnail": "cli13.jpg", "date":"July 18, 1998",      "url": "CLI13.WAD", "title": "CLi #13"                    ,"tocOffset":0,"shortConfig":true },
  { "editionID": "CLI14", "thumbnail": "cli14.jpg", "date":"December 22, 1998",  "url": "CLI14.WAD", "title": "CLi #14"                    ,"tocOffset":0,"shortConfig":true },
  { "editionID": "CLI15", "thumbnail": "cli15.jpg", "date":"March 2, 1999",      "url": "CLI15.WAD", "title": "CLi #15"                    ,"tocOffset":1},
  { "editionID": "CLI16", "thumbnail": "cli16.jpg", "date":"May 5, 1999",        "url": "CLI16.WAD", "title": "CLi #16"                    ,"tocOffset":1},
  { "editionID": "CLI17", "thumbnail": "cli17.jpg", "date":"July 8, 1999",       "url": "CLI17.WAD", "title": "CLi #17"                    ,"tocOffset":1},
  { "editionID": "CLI18", "thumbnail": "cli18.jpg", "date":"September 5, 1999",  "url": "CLI18.WAD", "title": "CLi #18"                    ,"tocOffset":1},
  { "editionID": "CLI19", "thumbnail": "cli19.jpg", "date":"November 7, 1999",   "url": "CLI19.WAD", "title": "CLi #19"                    ,"tocOffset":1},
  { "editionID": "CLI20", "thumbnail": "cli20.jpg", "date":"January 8, 2000",    "url": "CLI20.WAD", "title": "CLi #20"                    ,"tocOffset":1},
  { "editionID": "CLI21", "thumbnail": "cli21.jpg", "date":"March 13, 2000",     "url": "CLI21.WAD", "title": "CLi #21"                    ,"tocOffset":1},
  { "editionID": "CLI22", "thumbnail": "cli22.jpg", "date":"May 22, 2000",       "url": "CLI22.WAD", "title": "CLi #22"                    ,"tocOffset":1},
  { "editionID": "CLI23", "thumbnail": "cli23.jpg", "date":"July 5, 2000",       "url": "CLI23.WAD", "title": "CLi #23"                    ,"tocOffset":1},
  { "editionID": "CLI24", "thumbnail": "cli24.jpg", "date":"September 22, 2000", "url": "CLI24.WAD", "title": "CLi #24"                    ,"tocOffset":1},
  { "editionID": "CLI25", "thumbnail": "cli25.jpg", "date":"January 1, 2001",    "url": "CLI25.WAD", "title": "CLi #25"                    ,"tocOffset":1},
  { "editionID": "CLI26", "thumbnail": "cli26.jpg", "date":"March 1, 2001",      "url": "CLI26.WAD", "title": "CLi #26"                    ,"tocOffset":1},
  { "editionID": "CLI27", "thumbnail": "cli27.jpg", "date":"May 18, 2001",       "url": "CLI27.WAD", "title": "CLi #27"                    ,"tocOffset":1},
  { "editionID": "CLI28", "thumbnail": "cli28.jpg", "date":"July 6, 2001",       "url": "CLI28.WAD", "title": "CLi #28"                    ,"tocOffset":1},
  { "editionID": "CLI29", "thumbnail": "cli29.jpg", "date":"October 7, 2001",    "url": "CLI29.WAD", "title": "CLi #29"                    ,"tocOffset":1},
  { "editionID": "CLI30", "thumbnail": "cli30.jpg", "date":"December 11, 2001",  "url": "CLI30.WAD", "title": "CLi #30"                    ,"tocOffset":1},
  { "editionID": "CLI31", "thumbnail": "cli31.jpg", "date":"March 20, 2002",     "url": "CLI31.WAD", "title": "CLi #31"                    ,"tocOffset":1},
  { "editionID": "CLI32", "thumbnail": "cli32.jpg", "date":"June 15, 2002",      "url": "CLI32.WAD", "title": "CLi #32"                    ,"tocOffset":1},
  { "editionID": "CLI33", "thumbnail": "cli33.jpg", "date":"August 24, 2002",    "url": "CLI33.WAD", "title": "CLi #33 AntIQ Edition"      ,"tocOffset":1},
  { "editionID": "CLI34", "thumbnail": "cli34.jpg", "date":"October 23, 2002",   "url": "CLI34.WAD", "title": "CLi #34"                    ,"tocOffset":1},
  { "editionID": "CLI35", "thumbnail": "cli35.jpg", "date":"January 31, 2003",   "url": "CLI35.WAD", "title": "CLi #35"                    ,"tocOffset":1},
  { "editionID": "CLI36", "thumbnail": "cli36.jpg", "date":"April 23, 2003",     "url": "CLI36.WAD", "title": "CLi #36"                    ,"tocOffset":1},
  { "editionID": "CLI37", "thumbnail": "cli37.jpg", "date":"July 6, 2003",       "url": "CLI37.WAD", "title": "CLi #37 SceneCon Edition"   ,"tocOffset":1},
  { "editionID": "CLI38", "thumbnail": "cli38.jpg", "date":"September 28, 2003", "url": "CLI38.WAD", "title": "CLi #38"                    ,"tocOffset":1},
  { "editionID": "CLI39", "thumbnail": "cli39.jpg", "date":"December 24, 2003",  "url": "CLI39.WAD", "title": "CLi #39"                    ,"tocOffset":1},
  { "editionID": "CLI40", "thumbnail": "cli40.jpg", "date":"March 15, 2004",     "url": "CLI40.WAD", "title": "CLi #40"                    ,"tocOffset":1},
  { "editionID": "CLI41", "thumbnail": "cli41.jpg", "date":"June 25, 2004",      "url": "CLI41.WAD", "title": "CLi #41"                    ,"tocOffset":1},
  { "editionID": "CLI42", "thumbnail": "cli42.jpg", "date":"December 19, 2004",  "url": "CLI42.WAD", "title": "CLi #42"                    ,"tocOffset":1},
  { "editionID": "CLI43", "thumbnail": "cli43.jpg", "date":"March 15, 2006",     "url": "CLI43.WAD", "title": "CLi #43"                    ,"tocOffset":1},
  { "editionID": "CLI44", "thumbnail": "cli44.jpg", "date":"September 11, 2010", "url": "CLI44.WAD", "title": "CLi #44 Function X Edition" ,"tocOffset":1}
];