HUGI_ISSUES = [
  { "editionID":"HUGI18", "thumbnail": "hugi18.jpg", "url": "hugi18.dat", "date":"December 26, 1999", "title": "Hugi #18" },
  { "editionID":"HUGI19", "thumbnail": "hugi19.jpg", "url": "hugi19.dat", "date":"April 2000",        "title": "Hugi #19" },
  { "editionID":"HUGI20", "thumbnail": "hugi20.jpg", "url": "hugi20.dat", "date":"August 2000",       "title": "Hugi #20" },
  { "editionID":"HUGI21", "thumbnail": "hugi21.jpg", "url": "hugi21.dat", "date":"December 2000",     "title": "Hugi #21" },
  { "editionID":"HUGI22", "thumbnail": "hugi22.jpg", "url": "hugi22.dat", "date":"April 2001",        "title": "Hugi #22" },
  { "editionID":"HUGI23", "thumbnail": "hugi23.jpg", "url": "hugi23.dat", "date":"August 2001",       "title": "Hugi #23" },
  { "editionID":"HUGI24", "thumbnail": "hugi24.jpg", "url": "hugi24.dat", "date":"January 2002",      "title": "Hugi #24" },
  { "editionID":"HUGI25", "thumbnail": "hugi25.jpg", "url": "hugi25.dat", "date":"July 2002",         "title": "Hugi #25" },
  { "editionID":"HUGI26", "thumbnail": "hugi26.jpg", "url": "hugi26.dat", "date":"February 2003",     "title": "Hugi #26" },
  { "editionID":"HUGI27", "thumbnail": "hugi27.jpg", "url": "hugi27.dat", "date":"July 2003",         "title": "Hugi #27" },
  { "editionID":"HUGI28", "thumbnail": "hugi28.jpg", "url": "hugi28.dat", "date":"December 2003",     "title": "Hugi #28" },
  { "editionID":"HUGI29", "thumbnail": "hugi29.jpg", "url": "hugi29.dat", "date":"August 2004",       "title": "Hugi #29" },
  { "editionID":"HUGI30", "thumbnail": "hugi30.jpg", "url": "hugi30.dat", "date":"February 4, 2005",  "title": "Hugi #30" },
  { "editionID":"HUGI31", "thumbnail": "hugi31.jpg", "url": "hugi31.dat", "date":"October 31, 2005",  "title": "Hugi #31" },
  { "editionID":"HUGI32", "thumbnail": "hugi32.jpg", "url": "hugi32.dat", "date":"August 2006",       "title": "Hugi #32" },
  { "editionID":"HUGI33", "thumbnail": "hugi33.jpg", "url": "hugi33.dat", "date":"April 25, 2007",    "title": "Hugi #33" },
  { "editionID":"HUGI34", "thumbnail": "hugi34.jpg", "url": "hugi34.dat", "date":"February 2008",     "title": "Hugi #34" },
  { "editionID":"HUGI35", "thumbnail": "hugi35.jpg", "url": "hugi35.dat", "date":"November 2008",     "title": "Hugi #35" },
  { "editionID":"HUGI36", "thumbnail": "hugi36.jpg", "url": "hugi36.dat", "date":"April 2010",        "title": "Hugi #36" },
  { "editionID":"HUGI37", "thumbnail": "hugi37.jpg", "url": "hugi37.dat", "date":"April 1, 2012",     "title": "Hugi #37" },
  { "editionID":"HUGI38", "thumbnail": "hugi38.jpg", "url": "hugi38.dat", "date":"June 2014",         "title": "Hugi #38" }
];